import { useState } from "react";
import { AppWindow, BriefcaseBusiness, Check, ChevronRight, Link2, Plus, ShieldCheck, Users, X } from "lucide-react";
import { S, useThemeSingleton } from "../theme";

type BusinessProject = {
  id: string; name: string; model: string; platform: string; status: string; customers: string; revenue: string;
  apps: string[]; owner: string; benefits: Array<[string, string, string]>;
};

const projects: BusinessProject[] = [
  { id: "bp-001", name: "PRO会员增长计划", model: "健康会员 SCRM 模型", platform: "健康运营平台", status: "运营中", customers: "1,023", revenue: "¥28万/月", apps: ["主理人公社小程序", "企业微信 SCRM", "订单系统"], owner: "吴思远", benefits: [["PRO会员", "会员专属课、积分、优先服务", "已映射"], ["VIP", "私享活动、专属顾问", "已映射"]] },
  { id: "bp-002", name: "体验官转化计划", model: "健康会员 SCRM 模型", platform: "健康运营平台", status: "筹备中", customers: "387", revenue: "¥12万/月", apps: ["主理人公社小程序", "企业微信 SCRM"], owner: "刘刚", benefits: [["体验官", "体验礼包、打卡任务", "已映射"], ["PRO会员", "升级课程、社群优先服务", "待映射"]] },
  { id: "bp-003", name: "城市合伙人招募", model: "代理分销 SCRM 模型", platform: "商业城市平台", status: "运营中", customers: "300", revenue: "¥20万/月", apps: ["城市合伙人系统", "订单系统"], owner: "陈明", benefits: [["一级代理", "培训、区域权益、结算支持", "已映射"], ["二级代理", "区域任务、佣金结算", "已映射"]] },
];

const tabs = ["经营概览", "客户与权益", "应用连接", "团队与权限"] as const;

export default function BusinessProjectCenter() {
  useThemeSingleton();
  const [selectedId, setSelectedId] = useState(projects[0].id);
  const [tab, setTab] = useState<(typeof tabs)[number]>("经营概览");
  const [notice, setNotice] = useState("");
  const selected = projects.find(project => project.id === selectedId) ?? projects[0];
  const notify = (value: string) => { setNotice(value); window.setTimeout(() => setNotice(""), 2200); };

  return <div className="h-full overflow-auto p-6" style={{ background: S.bg, fontFamily: "monospace" }}>
    <header className="flex items-start justify-between gap-4 mb-5"><div><div className="flex items-center gap-2"><BriefcaseBusiness size={19} style={{ color: S.accent }} /><h1 className="m-0 text-lg font-bold" style={{ color: S.text }}>业务项目库</h1></div><p className="m-0 mt-1 text-xs" style={{ color: S.muted }}>管理真实经营项目：选择行业模型、连接业务应用、配置项目权益与运营团队</p></div><button type="button" onClick={() => notify("新建业务项目流程已打开")} className="flex items-center gap-1.5 px-3 py-2 text-xs font-bold" style={{ background: "#1e293b", color: S.accent, borderRadius: S.radiusSm }}><Plus size={14} />新建业务项目</button></header>

    <div className="grid grid-cols-[280px_minmax(0,1fr)] gap-4 min-h-[560px]">
      <aside className="p-3" style={{ background: S.surface, border: `1px solid ${S.border}`, borderRadius: S.radius }}><div className="text-xs font-bold mb-2" style={{ color: S.muted }}>业务项目 · {projects.length}</div>{projects.map(project => <button type="button" key={project.id} onClick={() => { setSelectedId(project.id); setTab("经营概览"); }} className="w-full text-left p-3 mb-2" style={{ background: selected.id === project.id ? S.accentLight : S.bg, border: `1px solid ${selected.id === project.id ? S.accent : S.border}`, borderRadius: S.radiusSm }}><div className="flex items-center justify-between gap-2"><span className="text-sm font-bold truncate" style={{ color: S.text }}>{project.name}</span><ChevronRight size={14} style={{ color: S.muted }} /></div><div className="text-[10px] mt-1 truncate" style={{ color: S.muted }}>{project.model}</div><div className="flex items-center justify-between mt-2"><span className="text-[10px] font-bold" style={{ color: project.status === "运营中" ? "#008565" : "#e77800" }}>{project.status}</span><span className="text-[10px]" style={{ color: S.muted }}>{project.platform}</span></div></button>)}</aside>
      <main className="min-w-0 p-5" style={{ background: S.surface, border: `1px solid ${S.border}`, borderRadius: S.radius }}><div className="flex items-start justify-between gap-3"><div><div className="flex items-center gap-2"><h2 className="m-0 text-base font-bold" style={{ color: S.text }}>{selected.name}</h2><span className="px-2 py-0.5 text-[10px] font-bold" style={{ background: selected.status === "运营中" ? "#e8fbf4" : "#fff0db", color: selected.status === "运营中" ? "#008565" : "#c2410c", borderRadius: 999 }}>{selected.status}</span></div><div className="text-[11px] mt-1" style={{ color: S.muted }}>基础行业模型：{selected.model} · 经营平台：{selected.platform}</div></div><button type="button" onClick={() => notify("已保存业务项目基础配置")} className="px-3 py-1.5 text-xs font-bold" style={{ background: S.accent, color: S.onPrimary, borderRadius: S.radiusSm }}>保存配置</button></div>
        <div className="flex gap-1 mt-5 p-1 overflow-x-auto" style={{ background: S.bg, border: `1px solid ${S.border}`, borderRadius: S.radiusSm }}>{tabs.map(item => <button type="button" key={item} onClick={() => setTab(item)} className="flex-1 min-w-max px-3 py-2 text-xs font-bold" style={{ background: tab === item ? "#1e293b" : "transparent", color: tab === item ? S.accent : S.muted, borderRadius: 6 }}>{item}</button>)}</div>
        {tab === "经营概览" && <div className="mt-5"><div className="grid grid-cols-3 gap-3">{[["客户", selected.customers], ["当前营收", selected.revenue], ["已连接应用", `${selected.apps.length} 个`]].map(([label, value]) => <div key={label} className="p-3" style={{ background: S.bg, border: `1px solid ${S.border}`, borderRadius: S.radiusSm }}><div className="text-[10px]" style={{ color: S.muted }}>{label}</div><div className="text-lg font-bold mt-1" style={{ color: S.text }}>{value}</div></div>)}</div><div className="mt-4 p-3 text-xs leading-relaxed" style={{ background: S.accentLight, border: `1px solid ${S.accentMid}`, borderRadius: S.radiusSm }}><b>模型与项目边界：</b>行业模型提供角色关系、客户分层和默认规则；当前业务项目才产生真实客户、订单、权益、服务和经营数据。</div></div>}
        {tab === "客户与权益" && <div className="mt-5 space-y-3"><div className="p-3 text-xs leading-relaxed" style={{ background: S.accentLight, border: `1px solid ${S.accentMid}`, borderRadius: S.radiusSm }}>权益规则属于当前业务项目。行业模型只提供默认模板，项目负责人可在此调整权益包与启用状态。</div>{selected.benefits.map(([level, benefit, mapping]) => <div key={level} className="grid grid-cols-[120px_1fr_auto] items-center gap-3 p-3" style={{ background: S.bg, border: `1px solid ${S.border}`, borderRadius: S.radiusSm }}><span className="text-xs font-bold" style={{ color: S.text }}>{level}</span><span className="text-xs" style={{ color: S.textSec }}>{benefit}</span><button type="button" onClick={() => notify(`${level} 权益调整申请已保存`)} className="px-2 py-1 text-[10px] font-bold" style={{ background: mapping === "已映射" ? "#e8fbf4" : "#fff0db", color: mapping === "已映射" ? "#008565" : "#c2410c", borderRadius: S.radiusSm }}>{mapping}</button></div>)}<button type="button" onClick={() => notify("新增项目权益包流程已打开")} className="w-full py-2 text-xs font-bold" style={{ border: `1px dashed ${S.borderMed}`, borderRadius: S.radiusSm }}><Plus size={13} className="inline mr-1" />新增项目权益包</button></div>}
        {tab === "应用连接" && <div className="mt-5 space-y-2"><div className="text-xs" style={{ color: S.muted }}>应用只负责项目权益展示、数据同步与业务动作回写，不定义项目规则。</div>{selected.apps.map((app, index) => <div key={app} className="flex items-center gap-3 p-3" style={{ background: S.bg, border: `1px solid ${S.border}`, borderRadius: S.radiusSm }}><div className="w-8 h-8 flex items-center justify-center" style={{ background: S.accentLight, color: "#5a6e00", borderRadius: S.radiusSm }}><AppWindow size={15} /></div><div className="flex-1"><div className="text-xs font-bold" style={{ color: S.text }}>{app}</div><div className="text-[10px] mt-0.5" style={{ color: S.muted }}>客户、权益与订单 {index === 2 ? "双向回写" : "已同步"}</div></div><button type="button" onClick={() => notify(`${app} 映射配置已打开`)} className="px-2 py-1 text-[10px] font-bold" style={{ border: `1px solid ${S.borderMed}`, borderRadius: S.radiusSm }}>配置映射</button></div>)}<button type="button" onClick={() => notify("应用连接流程已打开")} className="w-full py-2 text-xs font-bold" style={{ border: `1px dashed ${S.borderMed}`, borderRadius: S.radiusSm }}><Link2 size={13} className="inline mr-1" />连接业务应用</button></div>}
        {tab === "团队与权限" && <div className="mt-5 space-y-2">{[["项目负责人", selected.owner], ["服务团队", "吴思远、林小燕"], ["可见角色", "项目负责人、区域运营、客服"]].map(([label, value]) => <div key={label} className="flex items-center gap-3 p-3" style={{ background: S.bg, border: `1px solid ${S.border}`, borderRadius: S.radiusSm }}><div className="w-8 h-8 flex items-center justify-center" style={{ background: S.accentLight, color: "#5a6e00", borderRadius: S.radiusSm }}>{label === "可见角色" ? <ShieldCheck size={15} /> : <Users size={15} />}</div><div><div className="text-[10px]" style={{ color: S.muted }}>{label}</div><div className="text-xs font-bold mt-0.5" style={{ color: S.text }}>{value}</div></div></div>)}</div>}
      </main>
    </div>
    {notice && <div className="fixed bottom-6 right-6 z-50 flex items-center gap-2 px-4 py-3 text-sm" style={{ background: "#1e293b", color: S.accent, borderRadius: S.radiusSm, boxShadow: S.shadowLg }}><Check size={15} />{notice}<button type="button" aria-label="关闭提示" onClick={() => setNotice("")}><X size={14} /></button></div>}
  </div>;
}
